### ISSUE TITLE
arachni_web_task db:setup is not nonly creating db, but also resetting it if present

### ISSUE THREAD

**Issue by themr0c** [Arachni/arachni-ui-web#100]
Currently, if you run ````arachni_web_task db:setup```` on an instance connected with an existing database, the database will be reseted to the default values. Users created in the application will loose their access, and default users and passwords will be present again.

I believe that this script should only setup the database if tables or entries in tables are absent, but not reset it. What is your opinion on that matter ?

**Comment by Zapotek** [comment]
That's a standard Rails thing and I'm not willing to touch it.
I think you're looking for `db:migrate` though, which will upgrade your DB schema to the latest one.

What's your use case though?

**Comment by themr0c** [comment]
My case is: automating the installation of arachni with ansible, i would be more confident if i would have a command which create the db if it doesn't exist, but doesn't do anything on a running db. An eventual erroneous launch of this command would have no impact.

**Comment by Zapotek** [comment]
I'm afraid I can't help you with that, you'll have to check if a DB exists prior to running that command.

**Comment by themr0c** [comment]
OK. I am fine with that.
