### ISSUE TITLE
Global limit and number of scheduled scans

### ISSUE THREAD

**Issue by themr0c** [Arachni/arachni-ui-web#101]
"Global limit" is defined as "How many active scans to allow at any given time." 
As a user, i don't expect this limit to be the limit of scheduled scans, but as a limit which will permit the application to start the scheduled scans when a slot becomes available.

Actually, on nighly build, when I set Global limit, then i can't create a new scan, even if it is scheduled for later, when the number of active scans has reached the global limit.

Is my comprehension of "Global limit" erroneous ? or should the creation of new scans not be limited by the limit of active scans ?

**Comment by Zapotek** [comment]
The scheduler of the current WebUI isn't that advanced, so if the limit has been reached you can't create any new scans.

It's a bit stupid but will be resolved by the replacement which has a pretty awesome scheduler.

Cheers

**Comment by themr0c** [comment]
I guess it is possible, as a workaround, to unset the global limit when adding a new scan, and then set it up again? 
(To my understanding the number of scans should be = number of cores of the server, if it's a dedicated server.)

**Comment by Zapotek** [comment]
The workaround should work.
And one scan per core sounds about right, maybe 2 if you use less browser workers, depending on the CPU and RAM of course.
