### ISSUE TITLE
1.4 listening 9292

### ISSUE THREAD

**Issue by d4op** [Arachni/arachni-ui-web#105]
it doesnt matter on which serveri startup the webui.
it tells me listening on port 9292
nmap localhost, no 9292 listed.
firewall and iptables disabled.
doesnt matter which ruby version
ruby 2.2.0p0
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]

**Comment by Zapotek** [comment]
Can you show me how you started the server please?

**Comment by d4op** [comment]
cd bin 
./arachni_web
it tells me listening
Puma 2.14.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9292

**Comment by Zapotek** [comment]
What does your browser say when visiting http://localhst:9292?
Also, what's your OS?

Btw, Arachni isn't using any of the Ruby versions you mentioned, it actually bundle its own.

**Comment by d4op** [comment]
tested on centos and ubuntu servers.
i want to access it not via localhost, i want to access it via public ip.

**Comment by Zapotek** [comment]
In that case check out the bind options with `-h`, you can then specify your address and port of choice.

Cheers

**Comment by d4op** [comment]
ERR_CONNECTION_REFUSED when i want to connect, as i told ufw and iptables disbaled.

nmap localhost scan
Starting Nmap 7.01 ( https://nmap.org ) at 2016-02-11 10:36 CET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000070s latency).
Other addresses for localhost (not scanned): ::1
Not shown: 994 closed ports
PORT      STATE SERVICE
22/tcp    open  ssh
80/tcp    open  http
3306/tcp  open  mysql
9000/tcp  open  cslistener
10000/tcp open  snet-sensor-mgmt

Nmap done: 1 IP address (1 host up) scanned in 2.42 seconds

**Comment by d4op** [comment]
Ok working with -o publicip -p 1234
thanks

**Comment by Zapotek** [comment]
The interface probably used IPv6, you scanned IPv4 only.

`curl http://localhost:9292/` should verify that it is indeed working.

**Comment by d4op** [comment]
fixed.

**Comment by Zapotek** [comment]
Excellent, happy scanning.

**Comment by d4op** [comment]
btw may pin the footer to the bottom, looks ugly when the black part is moving up when the main content is to small.

**Comment by Zapotek** [comment]
I'll look into that.

If I may though, why did you deleted your replies?
Your question could help others.
