### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by iusky** [Arachni/arachni-ui-web#109]
root@arachni-virtual-machine:~/arachni-ui-web# rails 
Looks like your app's ./bin/rails is a stub that was generated by Bundler.

In Rails 4, your app's bin/ directory contains executables that are versioned
like any other source code, rather than stubs that are generated on demand.

Here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  rake rails:update:bin         # Use the new Rails 4 executables
  git add bin                   # Add bin/ to source control

You may need to remove bin/ from your .gitignore as well.

When you install a gem whose executable you want to use in your app,
generate it and add it to source control:

  bundle binstubs some-gem-name
  git add bin/new-executable

WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
      nokogiri (>= 1.5.9, ~> 1.6.0)
      rake (>= 0.8.7)
      thor (< 2.0, >= 0.18.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:33:in `block in setup': You have already activated activesupport 4.2.6, but your Gemfile requires activesupport 4.2.5.1. Using bundle exec may solve this. (Gem::LoadError)
    from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:19:in`setup'
    from /usr/lib/ruby/vendor_ruby/bundler.rb:120:in `setup'
    from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:7:in`<top (required)>'
    from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:114:in `require'
    from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:114:in`require'
    from /root/arachni-ui-web/config/boot.rb:14:in `<top (required)>'
    from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:114:in`require'
    from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:114:in `require'
    from /var/lib/gems/2.0.0/gems/railties-4.2.6/lib/rails/app_rails_loader.rb:44:in`block in exec_app_rails'
    from /var/lib/gems/2.0.0/gems/railties-4.2.6/lib/rails/app_rails_loader.rb:34:in `loop'
    from /var/lib/gems/2.0.0/gems/railties-4.2.6/lib/rails/app_rails_loader.rb:34:in`exec_app_rails'
    from /var/lib/gems/2.0.0/gems/railties-4.2.6/lib/rails/cli.rb:5:in `<top (required)>'
    from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:66:in`require'
    from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:66:in `require'
    from /var/lib/gems/2.0.0/gems/railties-4.2.6/bin/rails:9:in`<top (required)>'
    from /usr/local/bin/rails:23:in `load'
    from /usr/local/bin/rails:23:in`<main>'

**Comment by Zapotek** [comment]
Thanks for the heads up.

**Comment by Zapotek** [comment]
Btw, is there a reason you're working with the sources instead of using the provided self-contained [packages](http://www.arachni-scanner.com/download/)?
