### ISSUE TITLE
Postgres connections

### ISSUE THREAD

**Issue by treadie** [Arachni/arachni-ui-web#110]
Hi Tasos, Any chance you could add some exception handling to when DB connections fail to connect or use a Postgres database:

Ideally, covering the following two scenarios would be great:

1. Cant connect to server (whatever reason) > catch the exception, print whats wrong, and retry connection after 10 seconds. loop this until it connects, or the user forces an exit

2. no database schema setup > catch the exception and automatically run the `db:setup` as required

Cheers mate, this would help me out heaps.

**Comment by Zapotek** [comment]
Hello,

Unfortunately this is out of my control and is handled by Rails.
