### ISSUE TITLE
offer

### ISSUE THREAD

**Issue by lnkakalink** [Arachni/arachni-ui-web#117]
It is necessary to configure each site separately.
Nope full dens where work is underway.
login field on the site where to enter your username on the website or personal profile.
And as flow and pressure on the site.
In addition to 2 plug-ins need to do more and xss sql is not enough because these plugins include other types of vulnerabilities should be broken down by each type
and make common profile.
as it is necessary to pre-parse the site and then check and prisposoboit to answer many requests 429 the ideal scanner itself should determine the load site.

**Comment by Zapotek** [comment]
I'm not sure what you just said but the WebUI has stopped receiving new features as a replacement is in the works.

**Comment by lnkakalink** [comment]
Why WebUI has stopped?

**Comment by Zapotek** [comment]
The codebase is unmaintainable, it needs to be rewritten. The replacement will be much better but it's going to be a while before it's available.

**Comment by lnkakalink** [comment]
You will do a new version?

**Comment by Zapotek** [comment]
Not exactly a new version, it'll be a brand new interface.

**Comment by lnkakalink** [comment]
When you're ready?

**Comment by Zapotek** [comment]
I don't know yet.
