### ISSUE TITLE
rspec failures

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni-ui-web#119]
I have pulled arachni-web-ui and am running rspec. The majority of tests are failing.

```
ScansController
  GET index
F    assigns all scans as @scans (FAILED - 1)

NameError: undefined local variable or method `process_kill_em' for #<RSpec::ExampleGroups::ScansController before(:context) hook>
Did you mean?  process_kill
               process_kill_many
               process_kill_reactor
               process_killall
./spec/support/process_helper.rb:5:in `killall'
./spec/spec_helper.rb:32:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
```

I have traced this to the absence of  

> process_kill_em

from (I assume/home/brian/.rvm/gems/ruby-2.3.0/bundler/gems/arachni-84080db963b6/lib/arachni/processes/helpers/processes.rb) or perhaps elsewhere.

is there part of the build process I have missed.

**Comment by Zapotek** [comment]
Don't even bother, the specs for the WebUI have been abandoned for a long time and the WebUI itself has stopped receiving new features as a replacement is in the works.

**Comment by bgerardw** [comment]
Thanks

Out of curiosity, are the specs on the framework functioning?

**Comment by Zapotek** [comment]
Yep, but FYI they take a long time: https://github.com/Arachni/arachni/tree/experimental#running-the-specs
