### ISSUE TITLE
navbar-fixed-bottom covers part of page

### ISSUE THREAD

**Issue by MrScrudg** [Arachni/arachni-ui-web#121]
Hi, testing 07-Feb-2017 09:25  on win8.1x64
"navbar-fixed-bottom" covers some important parts of page:
![default](https://cloud.githubusercontent.com/assets/25591119/22703045/cee33952-ed73-11e6-9594-a4597eec2f7e.PNG)
Button "Update profile" in profile editor and some others are also covered

**Comment by Zapotek** [comment]
Closed via #122, pushing nightlies.

Thanks for the heads up.
