### ISSUE TITLE
just error as the picture

### ISSUE THREAD

**Issue by kingjohntom** [Arachni/arachni-ui-web#123]
[root@localhost arachni]# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Rubygems 1.8.25 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using rake 11.3.0
Using addressable 2.3.6
Using arachni-reactor 0.1.2
Using awesome_print 1.6.1
Using bundler 1.14.5
Installing ffi 1.9.17 with native extensions
Using coderay 1.1.0
Using concurrent-ruby 1.0.2
Installing http_parser.rb 0.6.0 with native extensions
Using kramdown 1.4.1
Using mini_portile2 2.1.0
Installing msgpack 0.7.0 with native extensions
Installing oj 2.15.0 with native extensions
Using oj_mimic_json 1.0.1
Installing ox 2.4.9 with native extensions
Using mime-types-data 3.2016.0521
Installing puma 2.14.0 with native extensions
Using rack 1.6.4
Using rb-readline 0.5.1
Using rubyzip 1.1.6
Using websocket 1.2.4
Using tilt 2.0.6
Using backports 3.6.8
Using multi_json 1.12.1
Using terminal-table 1.4.5
Using benchmark-ips 2.7.2
Using diff-lcs 1.3
Using docile 1.1.5
Using i18n 0.8.1
Installing json 2.0.3 with native extensions
Using memory_profiler 0.9.8
Using method_source 0.8.2
Using slop 3.6.0
Installing redcarpet 3.4.0 with native extensions
Using rspec-core 2.99.2
Using rspec-mocks 2.99.4
Using ruby-mass 0.1.3
Using simplecov-html 0.10.0
Installing stackprof 0.2.10 with native extensions
Using sys-proctable 1.1.3 (universal-linux)
Using yard 0.9.8
Using arachni-rpc 0.2.1.4
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native
extension.

        /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

Gem files will remain installed in /usr/local/share/gems/gems/ffi-1.9.17 for
inspection.
Results logged to /usr/local/share/gems/gems/ffi-1.9.17/ext/ffi_c/gem_make.out

An error occurred while installing ffi (1.9.17), and Bundler cannot
continue.
Make sure that `gem install ffi -v '1.9.17'` succeeds before bundling.

![st4l26u qy m6e75ti o _v](https://cloud.githubusercontent.com/assets/23326652/23395308/dee8f502-fdc8-11e6-8a9f-af8cbf1c9240.jpg)
![izu5vtmt n 1l 6bnxw_2x](https://cloud.githubusercontent.com/assets/23326652/23395324/eb36133a-fdc8-11e6-9a18-34d2f9dc14ea.jpg)
hi there ,i just build it in fedora ,at the last step, something wrong.
i didn't work  it out， any help will be fine.

**Comment by Zapotek** [comment]
You're missing the Ruby sources, I'm not sure how to install them in Fedora.
Why aren't you using the packages though instead of working with the source and having to deal with those dependency issues?
