### ISSUE TITLE
Minor issue - UI

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni-ui-web#124]
On the profiles page the menu options on the left are nor resizing as you resize the window. I noticed when I moved onto a laptop with a non standard screen size. To replicate just resize a browser window. It was visible on chrome and chromium.

**Comment by jugmac00** [comment]
Reproducable also on Internet Explorer and FireFox.

**Comment by Zapotek** [comment]
Thanks for the heads up, pushing nightlies with the fix now.
