### ISSUE TITLE
How to install this web-ui

### ISSUE THREAD

**Issue by ztencmcp** [Arachni/arachni-ui-web#126]
Hello,

Thanks for sharing this amazing tool, but I can't find any instructions about how to install web gui. May I ask you for help? Thanks

**Comment by tundeogunkoya** [comment]
If you are running on a windows machine,

What you need to do is to run the arachni_web file in the bin folder,

And then open your browser, go to  <http://localhost:9292> http://localhost:9292

Enter the username and password as 

 

Administrator:

        E-mail address: admin@admin.admin

        Password:       administrator

User:

        E-mail address: user@user.user

        Password:       regular_user

 

Good luck using the application

 

Regards

Tunde

**Comment by Zapotek** [comment]
There is nothing to install, [download](http://www.arachni-scanner.com/download/) a package and check out the README.
