### ISSUE TITLE
Export minor issue

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni-ui-web#129]
I have noticed that if a report runs and has an error in it, say a timeout, it is not possible to export the report in any format. In one case I Arachni has found a considerable number of issues and they can be accessed on interface but the conditional that shows the various export links is probably hiding those links.

**Comment by bgerardw** [comment]
Having looked at the error:

> The scan could no longer be monitored because connection with the Instance was lost. The Instance has probably encountered a fatal error and stopped.

I suspect I killed the app that I was testing and that caused the error and therefore the scan information can not be downloaded.

**Comment by Zapotek** [comment]
No, it's more likely that the OS killed the scanner instance, how many scans were you running at the same time and what are the machine's specs RAM-wise?

**Comment by bgerardw** [comment]
I may have had 3 scans running of my laptop with 8 gigs of ram.
What sort of specs are recommended.? How many scans should I run at once?

btw I ran some on my desktop and whenI tried to import them onto laptop, while the laptop was scanning, I noticed they did not upload properly, only a few results seemed to upload..  I had to wait till the scan had completed to get the upload to pull in all the vulnerabilities the scan on the desktop found.

**Comment by Zapotek** [comment]
Depends on the site really, generally about 2GB per scan but it can be more.

About the import, are you using SQLite?

**Comment by bgerardw** [comment]
I am using sqkite.

**Comment by Zapotek** [comment]
I probably couldn't handle the stress, consider using Postgres in the future.

**Comment by bgerardw** [comment]
Will do. That makes sense.
