### ISSUE TITLE
XXS proof seems bugged

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni-ui-web#130]
I did a test scan against http://zero.webappsecurity.com/.

It found an XXS vulnerability and  gave the following proof
 `#<Arachni::Parser::Nodes::Element:0x00000003db7a10>`

Is this working as intended?

Vector data:
Type	URL	Inputs
link	http://zero.webappsecurity.com/faq.html	
question	1<xss_538545b7ea67e47f516cb331ec938144/>

Scrrenshoted.

![proof](https://cloud.githubusercontent.com/assets/25486848/25181296/ff2a2df6-2508-11e7-8d9b-fdf1d8ad1ccc.png)

**Comment by Zapotek** [comment]
Fixed: https://github.com/Arachni/arachni/commit/d641941154fe003b03e286ae182a4f3a25812322
