### ISSUE TITLE
New Scan Advanced Defaults

### ISSUE THREAD

**Issue by Fenikkusu** [Arachni/arachni-ui-web#131]
Could admins get the ability to set the defaults of a new Scan? Right now it defaults to the Spinning off a new Instance if someone starts a scan. However, if we have setup a grid, I don't want it to spin off a new instance, I want it to use the already configured grid. I know when I create a scan to goto advanced and change it to the grid, but anyone else using the server isn't going to know to do that (or remember to do that if I tell them).

**Comment by Zapotek** [comment]
Unfortunately the WebUI has stopped receiving new features.
