### ISSUE TITLE
Scan does not seem to be making requests.

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni-ui-web#133]
I have kicked of a scan on the webui. Requests performed seems to be stuck on19027 but the scan timer is still running.

The output of the web app is just a call to service.native progress.

How should I proceed.

**Comment by Zapotek** [comment]
Is anything else going on in the stats? Timed-out requests, low HTTP request concurrency, high response times etc.?

**Comment by bgerardw** [comment]
It is rate limited to 5 per sec. Could that  be an issue?

**Comment by Zapotek** [comment]
It is worth a shot to disable that plugin.
Also, are there any errors?

**Comment by bgerardw** [comment]
Also I noticed that I have two different versions of the gem in the bundler folder. Maybe from unzipping the newer version.

**Comment by Zapotek** [comment]
Ah, that's a really bad idea, you can create conflicts.

**Comment by bgerardw** [comment]
No errors.Will clean it up to latest.

**Comment by bgerardw** [comment]
Rerunning and it seems to be fine. If I am scanning against a flaky site what setting would you recommend.

I do not want to knock it over.

**Comment by Zapotek** [comment]
Try lowering the HTTP request concurrency a lot and also reduce the amount of browsers workers in the browser-cluster's pool.
