### ISSUE TITLE
Problem running WEB UI

### ISSUE THREAD

**Issue by nan008** [Arachni/arachni-ui-web#134]
Hi, 

OS Centos 7 on AWS VM

I download and extracted the package. Running the command is not giving me any errors but it doesn't do anything

[root@security-01 arachni-1.5.1-0.5.12]# bin/arachni_web --host 0.0.0.0
Puma 2.14.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292

I added the 9292 to the security group on AWS with all the traffic allowed.

I am accessing the WEB UI using external ip address and port

But the Browser:

Unable to connect

Firefox can’t establish a connection to the server at xx.xxx.xxx.xx:9292.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

I am new to this app and ruby so can you tell me what I am doing wrong.

**Comment by Zapotek** [comment]
Hello,

This sounds like a networking issue and it's been a while since I've last played around with AWS, so I don't think I can be of much help.
Maybe try to debug this using something like netcat? Use the same host/port listening options and try to connect to it.

Also, try checking the AWS documentation on how to setup a server that is accessible from the outside.

**Comment by nan008** [comment]
So now I have a tips for you as I made it work on AWS.

- Need to allow all traffic in security not only the port that scanner is running on. 
- Allow all traffic on the target machine with the internal address of the Arachni server
- Need to run on IPv4 not IPv6 so start it with the --host 0.0.0.0 parameter


As we are running behind loadbalancer I need to now figure out how to pass user name and password so it would be accepted by LB as this is what is authenticating our web app.

Anyway thanks for help :)

**Comment by Zapotek** [comment]
Glad you go it working and thanks for the tip.
