### ISSUE TITLE
Profile update error

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni-ui-web#135]
I have edited a profile so the defaults for the proxy plugin have changed. I saved the profile and when I viewed I could see my changes, port is 8283 instead of 8282.

However, when I edit the profile again, the fields for the proxy plugin are populated by the defaults, not the new values. So if you edit the profile elsewhere say scope and are not paying attention you overwrite your changes in the proxy plugin with the defaults.

I did not check if this happens to other plugin settings.

**Comment by Zapotek** [comment]
Nighlties are up.
