### ISSUE TITLE
home site down

### ISSUE THREAD

**Issue by lesar** [Arachni/arachni-ui-web#154]
The www.arachni-scanner.com is not up by some day.  
 Error 522 Ray ID: 4e5a2e47af24d60c • 2019-06-12 07:41:40 UTC 
etc.

best regards,  
Leonardo

**Comment by Zapotek** [comment]
You're right, I've logged an issue with my hosting provider, the server seems to be down.

**Comment by Zapotek** [comment]
Fixed.
