### ISSUE TITLE
Show error - framework-v1.1 

### ISSUE THREAD

**Issue by whithajess** [Arachni/arachni-ui-web#82]
Getting:
`Encoding::CompatibilityError in Issues#show`

```
Showing arachni-ui-web/app/views/issues/show.html.erb where line #218 raised:

incompatible character encodings: UTF-8 and ASCII-8BIT
```

[Application Trace](https://gist.github.com/whithajess/17c0f54018b4726ae2ca)
[Framework Trace](https://gist.github.com/whithajess/600536a326b73cc5388a)
[Full Trace](https://gist.github.com/whithajess/4c967d6bd59443306564)

If you need more info let me know Cheers

**Comment by whithajess** [comment]
Was quite strange its the only one of those responses from the same scan as https://github.com/Arachni/arachni/issues/547 that gets labelled as CSRF instead of Backup directory.

If it helps here is the [response that caused the failure](https://gist.github.com/whithajess/39e1fe5508e699dbbbd2) using that example app should make it recreatable.

**Comment by whithajess** [comment]
This looks like it could be related to the Nokogiri issue. see https://github.com/sparklemotion/nokogiri/issues/845

**Comment by whithajess** [comment]
Not sure why but once the scan finished this error went away? I also get `The full report for this scan could not be retrieved due to an unknown error.`

**Comment by Zapotek** [comment]
Any errors in the terminal?

**Comment by whithajess** [comment]
Not that I can see doesn't seem to be anything in the logs at least after the scan has ran (I actually deleted the old logs derp) Im going to run this scan again and see if I can recreate until then I will close this.

**Comment by Zapotek** [comment]
There may be a stacktrace in the terminal output only, not in the logs, right after the report will be attempted to be retrieved/stored.

**Comment by whithajess** [comment]
Sorry should have been more clear I checked the terminal output as well and there wasn't anything there.

**Comment by Zapotek** [comment]
Hm, I'll have a look at error logging then. There should have been something in either the terminal, Rails logs or the errors associated with the scan.

**Comment by whithajess** [comment]
Ran the scan again this time there was no CSRF which doesn't help, but still the `The full report for this scan could not be retrieved due to an unknown error.` I didn't bother changing databases so still sqlite. Nothing in terminal or logs about the error. I checked out the version of nokogiri on the framework-v1.1 branch and it says `1.6.2.1` which is the failing one from https://github.com/Arachni/arachni/issues/543 it is hard to believe that one of the calls Arachni makes manages to get rails to send back malformed html (I tried to make it do this on purpose in some of my code with no luck) so any logging that could help would be much appreciated.

**Comment by Zapotek** [comment]
Better delete the existing log files prior to rescanning.

**Comment by whithajess** [comment]
Hey have ran this scan (after deleting logs and updating code) with no issues I believe the commit `82d8b31457f88a570b7cb751f2f87b72d18cc91b bundle update` that updated the broken nokogiri version just before the improve logged changes was the cause of this fix.

**Comment by Zapotek** [comment]
Hm, that's fair enough. Let me know if you run into any trouble.
