### ISSUE TITLE
URL rewrites added to profile

### ISSUE THREAD

**Issue by trotro** [Arachni/arachni-ui-web#84]
I try to add some url rewrites rules to a profile, but each time I try to update the profile, the rules are not added.

I tried with 2 format for my rule :
`/index-([0-9]+)-([0-9]+)\.html/:index.php?x=\1&mod_id=\2`
or 
`/index-(\d+)-(\d+)\.html/:index.php?x=\1&mod_id=\2`

In the web-ui logs I have
`Completed 200 OK in 60ms (Views: 48.3ms | ActiveRecord: 7.7ms)
Started PATCH "/profiles/4" for 80.93.83.20 at 2015-03-19 19:05:23 +0100
Processing by ProfilesController#update as HTML
  Parameters: {"utf8"=>"?", "authenticity_token"=>"dY4W2UMPEPc+FmjG7vze5J393s7WFiCSbBO5ps74uc0=", "profile"=>{"name"=>"My profile", "global"=>"0", "description"=>"LAMP based on default settings.", "user_ids"=>[""], "scope_https_only"=>"0", "scope_auto_redundant_paths"=>"5", "scope_directory_depth_limit"=>"", "scope_page_limit"=>"", "scope_include_subdomains"=>"0", "scope_exclude_binaries"=>"0", "scope_dom_depth_limit"=>"10", "scope_redundant_path_patterns"=>"index.php:5\r\nindex_extranet.php:5", "scope_exclude_content_patterns"=>"", "scope_exclude_path_patterns"=>"", "scope_include_path_patterns"=>"", "scope_restrict_paths"=>"", "scope_extend_paths"=>"", "scope_url_rewrites"=>"/index-([0-9]+)-([0-9]+)\\.html/:index.php?x=\\1&mod_id=\\2", "audit_forms"=>"1", "audit_links"=>"1", "audit_cookies"=>"0", "audit_headers"=>"0", "audit_with_both_http_methods"=>"0", "audit_cookies_extensively"=>"0", "audit_exclude_vector_patterns"=>"", "audit_include_vector_patterns"=>"", "audit_link_templates"=>"", "input_values"=>"(?i-mx:name)=arachni_name\r\n(?i-mx:user)=arachni_user\r\n(?i-mx:usr)=arachni_user\r\n(?i-mx:pass)=5543!%arachni_secret\r\n(?i-mx:txt)=arachni_text\r\n(?i-mx:num)=132\r\n(?i-mx:amount)=100\r\n(?i-mx:mail)=arachni@email.gr\r\n(?i-mx:account)=12\r\n(?i-mx:id)=1", "http_authentication_username"=>"", "http_authentication_password"=>"[FILTERED]", "http_request_concurrency"=>"5", "http_proxy_host"=>"", "http_request_redirect_limit"=>"5", "http_request_queue_size"=>"500", "http_proxy_port"=>"", "http_proxy_username"=>"", "http_proxy_password"=>"[FILTERED]", "http_proxy_type"=>"", "http_user_agent"=>"Arachni/v1.0.6", "http_request_timeout"=>"3000", "http_response_max_size"=>"1000000", "http_cookies"=>"", "http_request_headers"=>"", "no_fingerprinting"=>"0", "platforms"=>["linux", "", "mysql", "", "apache", "", "php", "", ""], "checks"=>["code_injection", "code_injection_php_input_wrapper", "code_injection_timing", "csrf", "file_inclusion", "ldap_injection", "no_sql_injection", "no_sql_injection_differential", "os_cmd_injection", "os_cmd_injection_timing", "path_traversal", "response_splitting", "rfi", "session_fixation", "source_code_disclosure", "sql_injection", "sql_injection_differential", "sql_injection_timing", "trainer", "unvalidated_redirect", "xpath_injection", "xss", "xss_dom", "xss_dom_inputs", "xss_dom_script_context", "xss_event", "xss_path", "xss_script_context", "xss_tag", "allowed_methods", "backdoors", "backup_directories", "backup_files", "captcha", "common_directories", "common_files", "cookie_set_for_parent_domain", "credit_card", "cvs_svn_users", "directory_listing", "emails", "form_upload", "hsts", "htaccess_limit", "html_objects", "http_only_cookies", "http_put", "insecure_cookies", "interesting_responses", "localstart_asp", "mixed_resource", "origin_spoof_access_restriction_bypass", "password_autocomplete", "private_ip", "ssn", "unencrypted_password_forms", "webdav", "xst"], "plugins"=>{"autologin"=>{"url"=>"", "parameters"=>"", "check"=>""}, "beep_notify"=>{"repeat"=>"4", "interval"=>"0.4"}, "content_types"=>{"exclude"=>"text"}, "cookie_collector"=>{"filter"=>""}, "email_notify"=>{"to"=>"", "cc"=>"", "bcc"=>"", "from"=>"", "server_address"=>"", "server_port"=>"", "username"=>"", "password"=>"[FILTERED]", "authentication"=>"plain", "report"=>"txt"}, "proxy"=>{"port"=>"8282", "bind_address"=>"0.0.0.0", "session_token"=>"", "timeout"=>"20000"}, "vector_feed"=>{"vectors"=>"", "yaml_string"=>""}, "waf_detector"=>{"precision"=>"5"}}, "selected_plugins"=>["autothrottle", "discovery", "healthmap", "timing_attacks", "uniformity"], "browser_cluster_pool_size"=>"4", "browser_cluster_job_timeout"=>"60", "browser_cluster_worker_time_to_live"=>"100", "browser_cluster_ignore_images"=>"1", "browser_cluster_screen_width"=>"1600", "browser_cluster_screen_height"=>"1200", "session_check_url"=>"", "session_check_pattern"=>""}, "commit"=>"Update Profile", "id"=>"4"}
Binary data inserted for `string` type on column `name`
Redirected to http://127.0.0.1:9292/profiles/4
Completed 302 Found in 151ms (ActiveRecord: 22.2ms)`

I check the database, and the rules are not added. Are my rules wrong ?
Or is it really a bug ?

**Comment by Zapotek** [comment]
This is a bug and has been fixed in the experimental branch, can you try the [nightlies](http://downloads.arachni-scanner.com/nightlies/) and let me know if they work please?

**Comment by trotro** [comment]
This issue is solved, thanks.
