### ISSUE TITLE
Authentication Scanning

### ISSUE THREAD

**Issue by ankitjraja** [Arachni/arachni-ui-web#88]
I would like to know that if authenticated scans can be performed using Arachni dashboard for windows.

**Comment by Zapotek** [comment]
Hello,

Just to be clear, are you using Arachni on Windows via the instructions on the experimental branch README?

**Comment by Zapotek** [comment]
Closing due to lack of feedback.

**Comment by nathandeandev** [comment]
hey, 
I have the same question, can arachni web dashboard support Authentication Scans, 
so suppose if I want to scan facebook and to scan facebook through Arachni, we need authenticated scan where we will enter the credentails, is this supported through web ui?
