### ISSUE TITLE
undefined local variable or method `process_kill_em' 

### ISSUE THREAD

**Issue by gh-flo-vall** [Arachni/arachni-ui-web#89]
In the ruby file /spec/support/process_helper.rb, there is a reference to the method process_kill_em.
https://github.com/Arachni/arachni-ui-web/blob/master/spec/support/process_helper.rb

```ruby
def killall
   instance_killall
   dispatcher_killall
   process_killall
   process_kill_em
end
```

This last one isn't defined in the file /lib/arachni/processes/helpers/processes.rb
https://github.com/Arachni/arachni/blob/master/lib/arachni/processes/helpers/processes.rb

```ruby
# @param (see Arachni::Processes::Manager#kill)
# @return (see Arachni::Processes::Manager#kill)
def process_kill( *args )
    Arachni::Processes::Manager.kill( *args )
end

# @param (see Arachni::Processes::Manager#killall)
# @return (see Arachni::Processes::Manager#killall)
def process_killall( *args )
    Arachni::Processes::Manager.killall( *args )
end

# @param (see Arachni::Processes::Manager#kill_many)
# @return (see Arachni::Processes::Manager#kill_many)
def process_kill_many( *args )
    Arachni::Processes::Manager.kill_many( *args )
end
```

It's now defined as kill_many in this file.

A proposed correction would be to change this reference in the process_helper.rb script.

**Comment by Zapotek** [comment]
As you can probably guess from the state of the specs (and the rest of the code), I gave up on them a long time ago.
The current WebUI in general is in limbo and will be retired and replaced, probably soon.

The only think I care about atm is that it's working.

I do appreciate you taking the time to let me know, but I can't bother with anything other than bugs in the app.

Cheers
