### ISSUE TITLE
Can not download scan report 

### ISSUE THREAD

**Issue by alvinhsian** [Arachni/arachni-ui-web#91]
I can not download the scan report after scanned a site, when I switch the database to PostgreSQL 9.4.4.

This is my database.yml settings:
==================================
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: arachni_development
  pool: 50
  username: arachni
  password: *****

test: &test
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: arachni_test
  pool: 50
  username: arachni
  password: *****

production: &production
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: arachni_production
  pool: 50
  username: arachni
  password: *****

cucumber:
 <<: *production

**Comment by Zapotek** [comment]
Can you retry using the [nightlies](http://downloads.arachni-scanner.com/nightlies/) please?
It contains a relevant bugfix which should take care of this problem.

**Comment by alvinhsian** [comment]
Thank you for your answer. How to change the application Listening on tcp://localhost:9292 to tcp://0.0.0.0:9292 ? Thanks!

**Comment by Zapotek** [comment]
No worries, if you pass the `-h` to `arachni_web` it'll show you the relevant options.
Let me know if the problem goes away so that I can close this issue.

Cheers

**Comment by alvinhsian** [comment]
Hello~~
Thank you for answer!! I have succeed!

**Comment by Zapotek** [comment]
No problem, cheers.
