### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by Consequences** [Arachni/arachni-ui-web#92]
I'm admittedly probably just a newbie when it comes to ruby/git/etc but I had a fair amount of difficulty getting started with this project because the Readme for the master branch is missing installation instructions. However, even after following the instructions from the other branches I'm still noticing that a binary (arachni_web_autostart or arachni_web) to run the webui as a daemon isn't ending up in any of the bin directories, nor does there appear to be a service for it.

I tried following instruction sets like: http://cyberpedia.in/arachni-web-application-scanner-in-kali-linux/ but that information seems very dated and the build of arachni in Kali repo currently does not include the webui as far as I can tell.

The obvious solution is to download and use the package from http://www.arachni-scanner.com/download/ but that too is lacking installation instructions. Also, using that package seems like it would make updating a lot more difficult than it would be if one was utilizing package management systems.

**Comment by Zapotek** [comment]
Hello,

There are no installation instructions, your best bet is to download one of the packages and create symblinks for its executables in `/bin` or place its bin directory in your `PATH`.

As for updating, you're right, it's a bit suboptimal, but this is the safest choice to run Arachni.

Cheers
