### ISSUE TITLE
AJAX refresh on scan status page drags focus to top of the page

### ISSUE THREAD

**Issue by sitsofe** [Arachni/arachni-ui-web#93]
Description of the problem:
When looking at the scan results page the page focus is peridoically moved to the top of the page.

Steps to reproduce:
1. Perform a scan that will produce results in four different categories.
2. Go to scan results page (e.g. http://scan.example.com:9292/scans/12 ) and resize the window to be 750 pixels tall.
3. Press page down.
4. Wait 15 seconds.

Expected result:
Page focus to stay where it initially was at step 3.

Actual result:
Page focus is moved to the top of the page (even after the scan is finished).

How reproducible is this problem?
It is reproducible every time.

Version information:
arachni-1.3.1-0.5.8-linux-x86_64
Chrome 45.0.2454.85 OS X

**Comment by Zapotek** [comment]
If you refresh after the resize does the problem go away?

**Comment by sitsofe** [comment]
Sadly it makes no difference - you can do the resizing as step 0, navigate to the scan page etc. and it still happens.

**Comment by Zapotek** [comment]
Works with Firefox but not Chrome, investigating.

**Comment by Zapotek** [comment]
`$('html, body').scrollTop()` worked in FF but not Chrome, `$('body').scrollTop()` works in both, so yay. :)

**Comment by Zapotek** [comment]
Nope, one works in FF, the other in Chrome, damn it to hell.

**Comment by Zapotek** [comment]
Forgot to mention, the fix can be found in the [nightlies](http://downloads.arachni-scanner.com/nightlies/).
The nightlies also include some [big changes](http://www.arachni-scanner.com/blog/massive-performance-optimizations-now-in-the-nightlies/), so if anything comes up please let me know.
