### ISSUE TITLE
Username with special character like é cause application error

### ISSUE THREAD

**Issue by themr0c** [Arachni/arachni-ui-web#94]
Way to reproduce:

1. Create a user without special characters in the name. 
2. Edit the user, add a special character in his name (like "é").
3. Validate. The change is accepted.
4. The user page cannot been displayed anymore. Instead the page is causing a 500 error

````
127.0.0.1 - - [18/Nov/2015:11:29:59 +0100] "PATCH /users/4 HTTP/1.1" 302 - 0.0292
127.0.0.1 - - [18/Nov/2015:11:29:59 +0100] "GET /500 HTTP/1.1" 500 643 0.0618
````

Can you please make sure either:
a. The application doesn't permit a username with special character (and gives a hint about allowed characters).
b. The application is usable with a username with a special character.
 
Additionally, it would be nice to have distinct fields for login name and display name.

**Comment by Zapotek** [comment]
I couldn't reproduce this, what's your version/OS/etc.?

**Comment by Zapotek** [comment]
I managed to reproduce it after resetting the DB, I'm on it.
Thanks for letting me know.

**Comment by Zapotek** [comment]
The issue has been resolved, I'll let you know once fresh nightlies are up.

About having different different fields for login and display names, the WebUI has stopped receiving new features as it's going to be replaced by a brand new web interface.

Cheers

**Comment by themr0c** [comment]
Many thanks ! Great to see how quick you were ! Will the new interface permit authentication with binding to a LDAP server (or SAML) ?

**Comment by Zapotek** [comment]
Don't know yet, I remember seeing a gem that provided support for LDAP but I'll cross that bridge when I get to it.

**Comment by Zapotek** [comment]
Nightlies are up, let me know how they work.

Cheers

**Comment by themr0c** [comment]
i am waiting for a scan to finish before changing anything, it's already running for 20 hours and discovered issues that netsparker hadn't found.

**Comment by Zapotek** [comment]
That's good, the current ones include a bug, pushing fresh ones now.

20 hours is bad though, is the server is really slow or just a huge webapp?

**Comment by themr0c** [comment]
That's a good question ... I use a single thread for now for each scan, and this night 3 scans were running concurrently from the server which is a 4 cores vm.

````
Pages discovered 	112 	Requests performed 	388837 	Requests per second 	6.03 	Request concurrency 	2
Running for 	19:49:09 	Responses received 	388817 	Timed out requests 	47560 	Response times 	1.810 s 
````

**Comment by Zapotek** [comment]
1.8s average response times, yeah the remote server isn't having a good time.
Arachni also throttled itself way down, to a request concurrency of 2, to avoid DoSing it.

Looks like it's going to be a while...

**Comment by themr0c** [comment]
maybe it's the work of the applicative firewall to slow down the connexions of the scanner which is surely now seen as an attacker.

**Comment by Zapotek** [comment]
That's a fair assumption, could very well be.
