### ISSUE TITLE
directories needing write access

### ISSUE THREAD

**Issue by themr0c** [Arachni/arachni-ui-web#95]
I wish the documentation would state that, when installing the package (zip), only following directories need write access for the user launching arachni. To me it seems to be an exhaustive list:

   - "{{ arachni_dir }}/system/arachni-ui-web/config/component_cache"
   - "{{ arachni_dir }}/system/arachni-ui-web/db"
   - "{{ arachni_dir }}/system/arachni-ui-web/tmp"
   - "{{ arachni_dir }}/system/logs"

**Comment by Zapotek** [comment]
There's also:

* `{{ arachni_dir }}/system/home`

I get your point though, I'll update the docs.

**Comment by themr0c** [comment]
thanks !

**Comment by Zapotek** [comment]
I think I better do this check when running the bin-wrappers and print an error if any or the aforementioned directories aren't writtable.
People tend to miss the docs.

**Comment by themr0c** [comment]
great !
