### ISSUE TITLE
"groups" have no effect on effective sharing of scans

### ISSUE THREAD

**Issue by themr0c** [Arachni/arachni-ui-web#97]
As i understand the usage of Groups, as described here https://github.com/Arachni/arachni-ui-web/wiki/scans, my expectation is following:

1. As User1, create a group Group1, and share with User2.
2. Assign a scan Scan1 to Group1.
3. As User2, you should now see the scan Scan1.

But as i see, point 3. is not a consequence of Scan1 being part of  Group1 shared with User2.

If, as User1, I share directly Scan1 with User2, User2 will see Scan1, though.

So either that's not the purpose of the Groups, and then their purpose should be better explained in the documentation, either the feature is somewhere borken.

**Comment by Zapotek** [comment]
Sounds like a bug, User2 should be able to see Scan1.
Looking into it.

**Comment by Zapotek** [comment]
I was able to verify that if User2 selects Group1 from the sidebar, Scan1 should appear in the `Shared` tab of the relevant category, based on its state.

Are you trying this behind your Apache proxy? It could be interfering again.

**Comment by themr0c** [comment]
So for you, it works without the additionnal operation of sharing the scan ? Adding to Group1 is sufficient ?

Yes it's again behind the proxy, you think it could interfere here also ? Is there any way i could run the app directly but secured via SSL ?

**Comment by Zapotek** [comment]
Yep, so long as the scan is in a group, all group members can see it.
The proxy could be interfering with the AJAX requests used to build the interface and whatnot, I've no idea.

People use Nginx for the same reasons and I haven't heard anything breaking.
I'm not sure how to do it directly, I'll have to look into it.

I'm switching full URLs to paths now, that could help.

**Comment by Zapotek** [comment]
To verify that this isn't a bug with the WebUI, can you try to reproduce the issue without the proxy please?

**Comment by themr0c** [comment]
In the nighly, running without apache proxy, the groups feature is working. The proxy is definitively the cause of all my trouble.

I will stop using this proxy i guess. I'll have a look at this option:

````
# config.force_ssl = true
````

Sorry for the noise.

**Comment by Zapotek** [comment]
That'll just use the `https://` in the URLs, I think. Not enable SSL.

No worries though, it happens.
