### ISSUE TITLE
How to download and use this?

### ISSUE THREAD

**Issue by Altiano** [Arachni/arachni-ui-web#98]

**Comment by Zapotek** [comment]
Download, extrack and check out the README: http://www.arachni-scanner.com/download/

**Comment by Altiano** [comment]
is it also include the web ui?

**Comment by Zapotek** [comment]
Yep, just check the README please.

**Comment by Altiano** [comment]
i wonder why don't you make any PPA for this?

**Comment by Zapotek** [comment]
I need fine control over the dependencies and don't have time maintaining different package types for different distributions.
The official packages however just work, extract and you're done.

**Comment by Altiano** [comment]
oh ok. thanks for the reply and for your hard work too.
